CREATE TABLE ETUDIANTS
(
    net int,
    nom varChar(255),
    age int
);
INSERT INTO ETUDIANTS
    (net,nom,age)
VALUES
    (0001, 'sample', 09);
ALTER TABLE ETUDIANTS ADD CONSTRAINT integrity PRIMARY KEY (age);
ALTER TABLE ETUDIANTS ADD  addresse varChar(255);


CREATE TABLE COUT
(
    age int,
    tarif int,
    CHECK (0<tarif),
    CHECK (tarif<4)
);
ALTER TABLE COUT ADD CONSTRAINT link FOREIGN KEY (age) REFERENCES ETUDIANTS(age);


INSERT INTO ETUDIANTS
    (net,nom,age)
VALUES
    (9999, 'me', 19);
INSERT INTO COUT
    (age,tarif)
VALUES
    (19, 2);

SELECT *
FROM ETUDIANTS INNER JOIN COUT ON ETUDIANTS.age=COUT.age;


ALTER TABLE COUT DROP CONSTRAINT link;
--ALTER TABLE ETUDIANTS DROP CONSTRAINT age;
ALTER TABLE ETUDIANTS DROP CONSTRAINT integrity;
DELETE FROM ETUDIANTS WHERE ETUDIANTS.age=COUT.age;

CREATE TABLE INSCRIPTION
(
    net int,
    diplome varChar(255)
);
ALTER TABLE ETUDIANTS ADD CONSTRAINT sameid PRIMARY KEY (net);
ALTER TABLE INSCRIPTION ADD CONSTRAINT sameid_ins FOREIGN KEY (net) REFERENCES ETUDIANTS(net);

--ON DLTE CASCADE