-- 1. Nom des villes avec monument sans renseignemet de prix
SELECT NOMV
FROM L2I_MONUMENT
WHERE PRIX = NULL;
-- 2. Nom des monuments qui contiennent au moins deux fois la lettre 'a'
SELECT NOMM
FROM L2I_MONUMENT
WHERE NOMM LIKE '%a%a%';
-- 3. Nom des clients ayants reserve il y a plus de trois ans
SELECT *
FROM L2I_RESER
WHERE (to_char(DATEDEP,'YYYY')) < '2016';
-- 4. Liste des reservations entre avril 2016 et 2017 (avril non inclus à chaque fois) ou en 2018 2019 et 2021
/*SELECT *
FROM L2I_RESER
WHERE (to_char(DATEDEP,'YYYY') BETWEEN '2016' AND '2017' AND DATEDEP NOT LIKE '%%-APR-%%';
*/--WRONG

-- 5. MONUMENT ni en france ni en Irlande
SELECT NOMM
FROM L2I_MONUMENT INNER JOIN L2I_VILLE ON L2I_MONUMENT.NOMV = L2I_VILLE.NOMV
WHERE L2I_VILLE.PAYS NOT LIKE 'France' AND L2I_VILLE.PAYS NOT LIKE 'Irlande';

--6.
SELECT NC, RANG
FROM L2I_CIRETAPE
WHERE NBJ = 5;

--7.
SELECT COUNT(*)
FROM L2I_CIRETAPE
WHERE VILET = 'Venise';
--8:
SELECT COUNT(DISTINCT(NOMC))
FROM L2I_RESER;

--9.

--10.

--11.

SELECT VILET
FROM L2I_CIRCUIT INNER JOIN L2I_RESER ON L2I_CIRCUIT.NC = L2I_RESER.NC RIGHT JOIN L2I_CIRETAPE ON L2I_CIRETAPE.NC=L2I_CIRCUIT.NC
WHERE NOMC = 'Picsou' AND PRIX > 200;
--12.


--13.


--14.


--15.

--SELECT * FROM L2I_CIRPROG INNER JOIN L2I_RESER ON L2I_RESER.NC = L2I_CIRPROG.NC; 
--SELECT * FROM L2I_CIRETAPE INNER JOIN L2I_CIRCUIT ON L2I_CIRCUIT.NC = L2I_CIRETAPE.NC;